### ISSUE TITLE
Please add support for haskell-src-exts 1.17.x

### ISSUE THREAD

**Issue by peti** [seereason/hsx2hs#5]
Hi, would it be possible to get a new release of `hsx2hs` that supports the latest `haskell-src-exts`? http://packdeps.haskellers.com/feed?needle=hsx2hs

**Comment by ddssff** [comment]
I will see about this.

**Comment by ddssff** [comment]
Version 0.13.4 is uploaded - let me know if it serves.

**Comment by peti** [comment]
The new version works: http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.hsx2hs.x86_64-linux. Thank you very much!
